// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PocketLedger.Data;

#nullable disable

namespace PocketLedger.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PocketLedgerDbContext))]
    partial class PocketLedgerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PocketLedger.Models.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<bool>("IncludeInMainBalance")
                        .HasColumnType("boolean")
                        .HasColumnName("include_in_main_balance");

                    b.Property<bool>("IncludeInNetWorth")
                        .HasColumnType("boolean")
                        .HasColumnName("include_in_net_worth");

                    b.Property<bool>("IncludeInStatistics")
                        .HasColumnType("boolean")
                        .HasColumnName("include_in_statistics");

                    b.Property<decimal>("InitialBalance")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("initial_balance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("OwnerId", "DisplayOrder")
                        .HasDatabaseName("ix_accounts_owner_id_display_order");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_category_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ix_categories_parent_category_id");

                    b.HasIndex("Type", "DisplayOrder")
                        .HasDatabaseName("ix_categories_type_display_order");

                    b.HasIndex("OwnerId", "Type", "DisplayOrder")
                        .HasDatabaseName("ix_categories_owner_id_type_display_order");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_not_self_referencing", "parent_category_id IS NULL OR parent_category_id <> id");

                            t.HasCheckConstraint("ck_categories_subcategory_icon", "parent_category_id IS NULL OR icon IS NULL");
                        });
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.Debt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("CounterpartyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("counterparty_name");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("direction");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("icon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<decimal>("OriginalAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("original_amount");

                    b.Property<Guid>("OwnerId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_debts");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_debts_account_id");

                    b.HasIndex("OwnerId", "Status")
                        .HasDatabaseName("ix_debts_owner_id_status");

                    b.ToTable("debts", null, t =>
                        {
                            t.HasCheckConstraint("ck_debts_date_range", "due_date IS NULL OR due_date >= start_date");

                            t.HasCheckConstraint("ck_debts_original_amount_positive", "original_amount > 0");

                            t.HasCheckConstraint("ck_debts_receivable_type", "direction <> 'Receivable' OR type = 'PrivatePerson'");
                        });
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.RecurringTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AdjustmentDirection")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("adjustment_direction");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<DateOnly>("AutomationStartsOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("automation_starts_on")
                        .HasDefaultValueSql("(CURRENT_TIMESTAMP AT TIME ZONE 'Europe/Budapest')::date");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("DebtId")
                        .HasColumnType("uuid")
                        .HasColumnName("debt_id");

                    b.Property<string>("DebtOperationType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("debt_operation_type");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<DateOnly>("FirstOccurrence")
                        .HasColumnType("date")
                        .HasColumnName("first_occurrence");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("frequency");

                    b.Property<DateOnly?>("LastOccurrence")
                        .HasColumnType("date")
                        .HasColumnName("last_occurrence");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("OwnerId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_recurring_transactions");

                    b.HasIndex("AccountId")
                        .HasDatabaseName("ix_recurring_transactions_account_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_recurring_transactions_category_id");

                    b.HasIndex("DebtId")
                        .HasDatabaseName("ix_recurring_transactions_debt_id");

                    b.HasIndex("Enabled", "FirstOccurrence")
                        .HasDatabaseName("ix_recurring_transactions_enabled_first_occurrence");

                    b.HasIndex("OwnerId", "Enabled", "FirstOccurrence")
                        .HasDatabaseName("ix_recurring_transactions_owner_id_enabled_first_occurrence");

                    b.ToTable("recurring_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_recurring_transactions_adjustment_direction", "(type = 'Adjustment' AND adjustment_direction IS NOT NULL) OR (type <> 'Adjustment' AND adjustment_direction IS NULL)");

                            t.HasCheckConstraint("ck_recurring_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_recurring_transactions_category", "(debt_id IS NOT NULL AND category_id IS NULL) OR (debt_id IS NULL AND type IN ('Income', 'Expense') AND category_id IS NOT NULL) OR (debt_id IS NULL AND type = 'Adjustment' AND category_id IS NULL)");

                            t.HasCheckConstraint("ck_recurring_transactions_date_range", "last_occurrence IS NULL OR last_occurrence >= first_occurrence");
                        });
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.RecurringTransactionOccurrence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("OccurrenceDate")
                        .HasColumnType("date")
                        .HasColumnName("occurrence_date");

                    b.Property<Guid>("OwnerId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("RecurringTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurring_transaction_id");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_recurring_transaction_occurrences");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_recurring_transaction_occurrences_owner_id");

                    b.HasIndex("TransactionId")
                        .IsUnique()
                        .HasDatabaseName("ux_recurring_transaction_occurrences_transaction_id");

                    b.HasIndex("RecurringTransactionId", "OccurrenceDate")
                        .IsUnique()
                        .HasDatabaseName("ux_recurring_transaction_occurrences_template_date");

                    b.ToTable("recurring_transaction_occurrences", (string)null);
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<string>("AdjustmentDirection")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("adjustment_direction");

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("amount");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("DebtId")
                        .HasColumnType("uuid")
                        .HasColumnName("debt_id");

                    b.Property<string>("DebtOperationType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("debt_operation_type");

                    b.Property<decimal?>("ExchangeRate")
                        .HasPrecision(19, 8)
                        .HasColumnType("numeric(19,8)")
                        .HasColumnName("exchange_rate");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<Guid>("OwnerId")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("SourceCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("source_currency")
                        .IsFixedLength();

                    b.Property<Guid?>("TargetAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_account_id");

                    b.Property<decimal?>("TargetAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("numeric(19,4)")
                        .HasColumnName("target_amount");

                    b.Property<string>("TargetCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("target_currency")
                        .IsFixedLength();

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<TimeOnly>("TransactionTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("transaction_time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("TargetAccountId")
                        .HasDatabaseName("ix_transactions_target_account_id");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("ix_transactions_transaction_date");

                    b.HasIndex("AccountId", "TransactionDate")
                        .HasDatabaseName("ix_transactions_account_id_transaction_date");

                    b.HasIndex("CategoryId", "TransactionDate")
                        .HasDatabaseName("ix_transactions_category_id_transaction_date");

                    b.HasIndex("DebtId", "TransactionDate")
                        .HasDatabaseName("ix_transactions_debt_id_transaction_date");

                    b.HasIndex("OwnerId", "TransactionDate")
                        .HasDatabaseName("ix_transactions_owner_id_transaction_date");

                    b.ToTable("transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_transactions_account", "(type = 'DebtEntry' AND account_id IS NULL) OR (type <> 'DebtEntry' AND account_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_transactions_adjustment_direction", "(type = 'Adjustment' AND adjustment_direction IS NOT NULL) OR (type <> 'Adjustment' AND adjustment_direction IS NULL)");

                            t.HasCheckConstraint("ck_transactions_amount_positive", "amount > 0");

                            t.HasCheckConstraint("ck_transactions_debt_operation", "(debt_id IS NULL AND debt_operation_type IS NULL) OR (debt_id IS NOT NULL AND debt_operation_type IS NOT NULL)");

                            t.HasCheckConstraint("ck_transactions_different_accounts", "target_account_id IS NULL OR target_account_id <> account_id");

                            t.HasCheckConstraint("ck_transactions_exchange_rate", "(type = 'Transfer' AND exchange_rate > 0 AND target_amount > 0 AND target_currency IS NOT NULL) OR (type <> 'Transfer' AND exchange_rate IS NULL AND target_amount IS NULL AND target_currency IS NULL)");

                            t.HasCheckConstraint("ck_transactions_target_amount_positive", "target_amount IS NULL OR target_amount > 0");

                            t.HasCheckConstraint("ck_transactions_target_amount_transfer", "target_amount IS NULL OR type = 'Transfer'");

                            t.HasCheckConstraint("ck_transactions_transfer_target", "(type = 'Transfer' AND account_id IS NOT NULL AND target_account_id IS NOT NULL) OR (type <> 'Transfer' AND target_account_id IS NULL)");
                        });
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.UserCurrencyFormat", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency_code")
                        .IsFixedLength();

                    b.Property<string>("CurrencyDisplay")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_display");

                    b.Property<string>("CurrencyPosition")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("currency_position");

                    b.Property<int>("DecimalPlaces")
                        .HasColumnType("integer")
                        .HasColumnName("decimal_places");

                    b.Property<string>("DecimalSeparator")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("decimal_separator");

                    b.Property<string>("ThousandsSeparator")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("thousands_separator");

                    b.Property<bool>("UseSpace")
                        .HasColumnType("boolean")
                        .HasColumnName("use_space");

                    b.HasKey("UserId", "CurrencyCode");

                    b.ToTable("user_currency_formats", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_currency_formats_decimal_places", "decimal_places BETWEEN 0 AND 4");

                            t.HasCheckConstraint("ck_user_currency_formats_separators", "decimal_separator <> thousands_separator");
                        });
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("AvatarId")
                        .HasColumnType("integer")
                        .HasColumnName("avatar_id");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("default_currency")
                        .IsFixedLength();

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.HasKey("UserId");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.Category", b =>
                {
                    b.HasOne("PocketLedger.Models.Entities.Category", "ParentCategory")
                        .WithMany("Subcategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_category_id");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.Debt", b =>
                {
                    b.HasOne("PocketLedger.Models.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_debts_accounts_account_id");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.RecurringTransaction", b =>
                {
                    b.HasOne("PocketLedger.Models.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_transactions_accounts_account_id");

                    b.HasOne("PocketLedger.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recurring_transactions_categories_category_id");

                    b.HasOne("PocketLedger.Models.Entities.Debt", "Debt")
                        .WithMany("RecurringTransactions")
                        .HasForeignKey("DebtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recurring_transactions_debts_debt_id");

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("Debt");
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.RecurringTransactionOccurrence", b =>
                {
                    b.HasOne("PocketLedger.Models.Entities.RecurringTransaction", "RecurringTransaction")
                        .WithMany("Occurrences")
                        .HasForeignKey("RecurringTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recurring_transaction_occurrences_recurring_transaction_id");

                    b.HasOne("PocketLedger.Models.Entities.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recurring_transaction_occurrences_transactions_transaction_id");

                    b.Navigation("RecurringTransaction");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.Transaction", b =>
                {
                    b.HasOne("PocketLedger.Models.Entities.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_accounts_account_id");

                    b.HasOne("PocketLedger.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_categories_category_id");

                    b.HasOne("PocketLedger.Models.Entities.Debt", "Debt")
                        .WithMany("Transactions")
                        .HasForeignKey("DebtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_debts_debt_id");

                    b.HasOne("PocketLedger.Models.Entities.Account", "TargetAccount")
                        .WithMany()
                        .HasForeignKey("TargetAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_accounts_target_account_id");

                    b.Navigation("Account");

                    b.Navigation("Category");

                    b.Navigation("Debt");

                    b.Navigation("TargetAccount");
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.UserCurrencyFormat", b =>
                {
                    b.HasOne("PocketLedger.Models.Entities.UserPreference", "User")
                        .WithMany("CurrencyFormats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.Category", b =>
                {
                    b.Navigation("Subcategories");
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.Debt", b =>
                {
                    b.Navigation("RecurringTransactions");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.RecurringTransaction", b =>
                {
                    b.Navigation("Occurrences");
                });

            modelBuilder.Entity("PocketLedger.Models.Entities.UserPreference", b =>
                {
                    b.Navigation("CurrencyFormats");
                });
#pragma warning restore 612, 618
        }
    }
}
