using PocketLedger.Contracts;
using PocketLedger.Models.Entities;
using PocketLedger.Services;
using PocketLedger.Services.Interfaces;

namespace PocketLedger.Web.Api;

internal static class WebContractMapper
{
    public static CurrencyBalance ToServiceModel(this CurrencyBalanceDto value) => new(value.Currency, value.Amount);
    public static AccountDto ToDto(this Account value) => new(value.Id, value.Name, value.Type, value.Currency, value.InitialBalance, value.Icon, value.Color, value.DisplayOrder, value.IncludeInMainBalance, value.IncludeInNetWorth, value.IncludeInStatistics);
    public static Account ToEntity(this AccountDto value) => new() { Id = value.Id, Name = value.Name, Type = value.Type, Currency = value.Currency, InitialBalance = value.InitialBalance, Icon = value.Icon, Color = value.Color, DisplayOrder = value.DisplayOrder, IncludeInMainBalance = value.IncludeInMainBalance, IncludeInNetWorth = value.IncludeInNetWorth, IncludeInStatistics = value.IncludeInStatistics };
    public static CategoryDto ToDto(this Category value) => new(value.Id, value.Name, value.Type, value.Icon, value.ParentCategoryId, null, [], value.DisplayOrder);
    public static Category ToEntity(this CategoryDto value) => new() { Id = value.Id, Name = value.Name, Type = value.Type, Icon = value.Icon, ParentCategoryId = value.ParentCategoryId, ParentCategory = value.ParentCategory?.ToEntity(), Subcategories = value.Subcategories.Select(ToEntity).ToList(), DisplayOrder = value.DisplayOrder };
    public static DebtDto ToDto(this Debt value) => new(value.Id, value.Name, value.Icon, value.Direction, value.Type, value.CounterpartyName, value.OriginalAmount, value.Currency, value.StartDate, value.DueDate, value.Note, value.Status, value.ClosedAt, value.AccountId, value.Account?.ToDto());
    public static Debt ToEntity(this DebtDto value) => new() { Id = value.Id, Name = value.Name, Icon = value.Icon, Direction = value.Direction, Type = value.Type, CounterpartyName = value.CounterpartyName, OriginalAmount = value.OriginalAmount, Currency = value.Currency, StartDate = value.StartDate, DueDate = value.DueDate, Note = value.Note, Status = value.Status, ClosedAt = value.ClosedAt, AccountId = value.AccountId, Account = value.Account?.ToEntity() };
    public static RecurringTransactionDto ToDto(this RecurringTransaction value) => new(value.Id, value.Type, value.AccountId, value.Account?.ToDto(), value.CategoryId, value.Category?.ToDto(), value.Amount, value.AdjustmentDirection, value.Note, value.FirstOccurrence, value.LastOccurrence, value.AutomationStartsOn, value.Frequency, value.Enabled, value.DebtId, value.Debt?.ToDto(), value.DebtOperationType);
    public static RecurringTransaction ToEntity(this RecurringTransactionDto value) => new() { Id = value.Id, Type = value.Type, AccountId = value.AccountId, Account = value.Account?.ToEntity()!, CategoryId = value.CategoryId, Category = value.Category?.ToEntity(), Amount = value.Amount, AdjustmentDirection = value.AdjustmentDirection, Note = value.Note, FirstOccurrence = value.FirstOccurrence, LastOccurrence = value.LastOccurrence, AutomationStartsOn = value.AutomationStartsOn, Frequency = value.Frequency, Enabled = value.Enabled, DebtId = value.DebtId, Debt = value.Debt?.ToEntity(), DebtOperationType = value.DebtOperationType };
    public static TransactionDto ToDto(this Transaction value) => new(value.Id, value.Type, value.AccountId, value.Account?.ToDto(), value.TargetAccountId, value.TargetAccount?.ToDto(), value.Amount, value.TargetAmount, value.ExchangeRate, value.SourceCurrency, value.TargetCurrency, value.AdjustmentDirection, value.TransactionDate, value.TransactionTime, value.OccurredAtUtc, value.CategoryId, value.Category?.ToDto(), value.Note, value.DebtId, value.Debt?.ToDto(), value.DebtOperationType);
    public static TransactionCreateRequest ToRequest(this TransactionCreateInput value) => new(value.Type, value.AccountId, value.TargetAccountId, value.Amount, value.TargetAmount, value.ExchangeRate, value.AdjustmentDirection, value.TransactionDate, value.TransactionTime, value.CategoryId, value.Note);
    public static TransactionUpdateRequest ToRequest(this TransactionUpdateInput value) => new(value.Type, value.AccountId, value.TargetAccountId, value.Amount, value.TargetAmount, value.ExchangeRate, value.AdjustmentDirection, value.TransactionDate, value.TransactionTime, value.CategoryId, value.Note);
    public static Transaction ToEntity(this TransactionDto value) => new() { Id = value.Id, Type = value.Type, AccountId = value.AccountId, Account = value.Account?.ToEntity(), TargetAccountId = value.TargetAccountId, TargetAccount = value.TargetAccount?.ToEntity(), Amount = value.Amount, TargetAmount = value.TargetAmount, ExchangeRate = value.ExchangeRate, SourceCurrency = value.SourceCurrency, TargetCurrency = value.TargetCurrency, AdjustmentDirection = value.AdjustmentDirection, TransactionDate = value.TransactionDate, TransactionTime = value.TransactionTime, OccurredAtUtc = value.OccurredAtUtc, CategoryId = value.CategoryId, Category = value.Category?.ToEntity(), Note = value.Note, DebtId = value.DebtId, Debt = value.Debt?.ToEntity(), DebtOperationType = value.DebtOperationType };
    public static DebtSummary ToServiceModel(this DebtSummaryResponse value) => new(value.Debt.ToEntity(), value.RemainingAmount, value.AutomaticPayment?.ToEntity(), value.NextPayment);
    public static DebtDetails ToServiceModel(this DebtDetailsResponse value) => new(value.Debt.ToEntity(), value.RemainingAmount, value.Transactions.Select(ToEntity).ToArray(), value.AutomaticPayment?.ToEntity(), value.NextPayment);
    public static PagedResult<Transaction> ToServiceModel(this PagedResponse<TransactionDto> value) => new(value.Items.Select(ToEntity).ToArray(), value.TotalCount, value.Page, value.PageSize);
}
